name: Build BossPlugin

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build Project with Maven
        run: mvn clean package --batch-mode

      - name: Save BossPlugin JAR
        uses: actions/upload-artifact@v4
        with:
          name: BossPlugin-JAR
          path: target/*.jar
